name: 'coreload_proj' # profiles.yml에 정의된 프로필 이름과 일치해야 함
version: '1.0.0'
config-version: 1

profile: 'coreload_proj' # profiles.yml의 프로필 이름

model-paths: ["models"]
macro-paths: ["macros"]

models:
  coreload_proj:
    staging:
      +materialized: view
    marts:
      +materialized: table